### ISSUE TITLE
pagination & use of cursor  (crossref.org)

### ISSUE THREAD

**Issue by jimrothstein** [r4ds/bookclub-wapir#49]
Slide:   httr2-pagination.qmd

In video, you did cover 
- add user-agent to be good citizen 
- crossref.org can return A lot of data.

Regretably, some of us have to do it wrong anyway.   So this suggestion, perhaps as footnote,  is only to add emphasis:   READ the docs!

(1) 
[Good manners = more reliable service ](https://api.crossref.org/swagger-ui/index.html)

> "But we prefer carrots to sticks. As of September 18th 2017 any API queries that use HTTPS and have appropriate contact information will be directed to a **special pool of API machines that are reserved for polite user**s." <emphasis added><snip>

(2) TIPS ...
https://www.crossref.org/documentation/retrieve-metadata/rest-api/tips-for-using-the-crossref-rest-api/
**Don’t use rows and offsets to page through the /works route . They are very expensive and slow. Use cursors instead.**

**Comment by jonthegeek** [comment]
As I mentioned in the meeting, thank you for this! I added user agent info to the Auth chapter because of this, and will definitely talk more about manners & looking for this sort of things in docs in the next iteration of the earlier chapters!
