### ISSUE TITLE
OAUTH 2.1 (draft)

### ISSUE THREAD

**Issue by jimrothstein** [r4ds/bookclub-wapir#56]
This is current DRAFT for OAUTH 2.1 (https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-10), `valid till July 2024`.

It is readable !     I will have it stenciled on my t-shirts!

Removes some clutter related to now obsolete methods (passwords, etc) and well-written,  just loaded down with vocabulary.

Can not find reference to REVOKING access token.

Hope you adopt same language as in the DRAFT.  And let people know document `exists` and is the `standard` when searching for information or implementation of authorization and access to resources.

 Still hazy about `BEARER` token;  `2012 spec` referred to these as one type of accesss token (ie a `flavor`).   Until I learn otherwise, I prefer to say 'bearer token' is just one  type of `access token`
```
For example:

HTTP/1.1 200 OK
Content-Type: application/json
Cache-Control: no-store

{
  "access_token":"2YotnFZFEjr1zCsicMWpAA",
  "token_type":"Bearer",
  "expires_in":3600,
  "refresh_token":"tGzv3JOkF0XG5Qx2TlKWIA",
  "example_parameter":"example_value"
}
```

NEXT:   attempt to match `httr2` functions to key words in OAUTH 2.1

**Comment by jonthegeek** [comment]
This may be referenced in the plumber half of the book. It mostly compiles suggestions from previous RFCs, so it's a useful reference in that regard. Thanks!

As for bearer tokens vs access tokens... they're kinda a type of each other.

- Bearer tokens are a distinct type of authorization header, defined outside of oauth2. They're passed in the `Authorization` header, and begin with "Bearer "
- Technically "bearer token" could also be used as a generic term for "a token that grants access without any separate identification component," but in practice I believe the term is always used for the specific type of header.
- OAuth2 access tokens can theoretically be any sort of token (eg, a query parameters named "MyUniqueAccessToken"), but in practice they're always bearer tokens, as far as I've seen. For example, see `?httr2::oauth_token`, which has a `token_type` field, but the only valid value is `"bearer"`.
